### ISSUE TITLE
PHP syntax

### ISSUE THREAD

**Issue by zomfg** [szepeviktor/multipart-robotstxt-editor#2]
Would it be possible for you to hold on to the older syntax for now, please?
I'm talking about keeping ye old `array()` instead of `[]`, and same for `foo()[0]` decomposing.
They don't provide any real advantage in this case and break your very useful plugin on older PHP versions (5.3 in my case).
Also PHP version requirements aren't mentioned anywhere it seems :(

Cheers

**Comment by szepeviktor** [comment]
OK.
PR-s are welcome.
I think this one is quite easy.
