### ISSUE TITLE
PHP Fatal error:  require_once(): Failed opening required 'includes/robotstxtparser.php'

### ISSUE THREAD

**Issue by Blade95uk** [szepeviktor/multipart-robotstxt-editor#4]
/wp-content/plugins/multipart-robotstxt-editor/mp-robotstxt.php on line 85

```
// Prettify
        require_once 'includes/robotstxtparser.php';
        $parser = new RobotsTxtParser( $robotstxt );
        $robotstxt = $parser->render();

```

**Comment by szepeviktor** [comment]
Hello @Blade95uk !

Try

```php
require_once dirname( __FILE__ ) . '/includes/robotstxtparser.php';
```

**Comment by Blade95uk** [comment]
No I manage to fix it, on the WordPress site you forgot to include the folder includes with the class file in

**Comment by szepeviktor** [comment]
Oh! Thank you!

Fixing now: https://plugins.trac.wordpress.org/log/multipart-robotstxt-editor/

**Comment by Blade95uk** [comment]
Your lucky, i can code n php and review error logs ;)

**Comment by szepeviktor** [comment]
Actually I do not use and develop my plugins that have UI as I only provide infrastructure for clients.
All the used and updated plugins are in the installation docs: https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/WordPress.md#plugins

**Comment by Blade95uk** [comment]
Not a huge fan of front end, but i do enjoy back end coding. good old shell <3, i should really use a vps then a shared server more to customize whats installed (su) apt-get ffmepg libavtools
